=== saida-ben/json_project/Users.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Lp">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Users"/>
        <xs:element name="Roles"/>
        <xs:element name="Permissions"/>

      </xs:sequence>
    </xs:complexType>
         <xs:key name="PermissionIdKey">
        <xs:selector xpath="Permissions/Permission"/>
        <xs:field xpath="nom"/>
      </xs:key>
        <xs:key name="UserIdKey">
        <xs:selector xpath="Users/User"/>
        <xs:field xpath="email"/>
      </xs:key>
       <xs:key name="RoleIdKey">
        <xs:selector xpath="Roles/Role"/>
        <xs:field xpath="nom"/>
      </xs:key>
        
      <xs:keyref name="RolePermissionsRef" refer="PermissionIdKey">
        <xs:selector xpath="Roles/Role"/>
        <xs:field xpath="permission"/>
      </xs:keyref>
      <xs:keyref name="RoleUsersRef" refer="RoleIdKey">
        <xs:selector xpath="Users/User"/>
        <xs:field xpath="role"/>
      </xs:keyref>
      </xs:element>
      
    
   <xs:element name="Users">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="User" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<xs:element name="Roles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Role" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Permissions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Permission" minOccurs="1" maxOccurs="unbounded"/>

      </xs:sequence>
    </xs:complexType>
        
  </xs:element>
  <xs:element name="User">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="prenom" type="xs:string"/>
        <xs:element name="email" type="xs:string"/>
        <xs:element name="role" type="xs:string"/>
      </xs:sequence>
      
    </xs:complexType>
  
  </xs:element>

  <xs:element name="Role">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="permission" type="xs:string"/>
      </xs:sequence>
    
    </xs:complexType>
     
  </xs:element>

  <xs:element name="Permission">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
      </xs:sequence>
      
    </xs:complexType>
  
  </xs:element>

</xs:schema>

=== saida-ben/json_project/Users.xml
<?xml-stylesheet type="text/xsl" href="affichage.xsl"?>

<Lp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Users.xsd">
  <Users>
    <User>
      <nom>El bouazzaoui</nom>
      <prenom>ahmad</prenom>
      <email>ahmad@gmail.com</email>
      <role>Admin</role>
    </User>
    <User>
      <nom>Said</nom>
      <prenom>Mohammad</prenom>
      <email>mohammad@gmail.com</email>
      <role>Directeur</role>
    </User>
    <User>
      <nom>Elou</nom>
      <prenom>jamal</prenom>
      <email>jamal@gmail.com</email>
      <role>Responsable_filiere</role>
    </User>
    <User>
      <nom>Elou</nom>
      <prenom>saida</prenom>
      <email>saida@gmail.com</email>
      <role>Condidat</role>
    </User>
  </Users>
  <Roles>
    <Role>
      <nom>Directeur</nom>
      <permission>consulter_la_liste_des_condidats</permission>
    </Role>
    <Role>
      <nom>Admin</nom>
      <permission>creerUser</permission>
    </Role>
    <Role>
      <nom>Responsable_filiere</nom>
      <permission>accepter_candidat</permission>
    </Role>
   
    <Role>
      <nom>Condidat</nom>
      <permission>consulter_demande</permission>
    </Role>
  </Roles>
  <Permissions>
    <Permission>
      <nom>consulter_la_liste_des_condidats</nom>
    </Permission>
    <Permission>
      <nom>consulter_demande</nom>
    </Permission>
    <Permission>
      <nom>accepter_candidat</nom>
    </Permission>
    <Permission>
      <nom>creerUser</nom>
    </Permission>
  </Permissions>
</Lp>
